import { TheHeader } from "@/components/header";
import "./globals.css";
import { Inter, Lato, Montserrat } from "next/font/google";
import { TheFooter } from "@/components/footer";
import Head from "next/head";

const montserrat = Montserrat({
  subsets: ["cyrillic", "latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Venkon Com.",
  description:
    "Generated by create next app | see /about for more information.",
  link: "",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html>
        <Head>
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
            crossorigin="anonymous"
          />
        </Head>
        <body className={montserrat.className}>
          <div className="wrapper">
            <TheHeader />
            <main className="my-container">{children}</main>
            <TheFooter />
          </div>
        </body>
      </html>
    </>
  );
}
